# Generated by Django 4.1.3 on 2023-02-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rmc", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Degree",
            new_name="Staff",
        ),
    ]
