# Generated by Django 4.1.3 on 2023-02-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rmc", "0004_alter_degreeprogramme_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="email",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Email"
            ),
        ),
    ]
