# Generated by Django 4.1.3 on 2023-02-28 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rmc", "0005_staff_email_student_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="degreeprogramme",
            name="programme_courses",
        ),
    ]
