# Generated by Django 4.1.3 on 2023-02-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rmc", "0006_remove_degreeprogramme_programme_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="degreeprogramme",
            name="programme_courses",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="programme_courses", to="rmc.course"
            ),
        ),
    ]
