# Generated by Django 4.1.3 on 2023-02-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rmc", "0007_degreeprogramme_programme_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="degreeprogramme",
            name="programme_courses",
            field=models.ManyToManyField(
                related_name="programme_courses", to="rmc.course"
            ),
        ),
    ]
