# Generated by Django 4.1.3 on 2023-02-28 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rmc", "0008_alter_degreeprogramme_programme_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="degreeprogramme",
            name="programme_courses",
        ),
        migrations.RemoveField(
            model_name="course",
            name="associated_degree_programme",
        ),
        migrations.AddField(
            model_name="course",
            name="associated_degree_programme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="associated_degree_programme",
                to="rmc.degreeprogramme",
            ),
        ),
    ]
