# Generated by Django 4.1.3 on 2023-02-28 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rmc", "0009_remove_degreeprogramme_programme_courses_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="associated_degree_programme",
            new_name="degree",
        ),
    ]
