# Generated by Django 4.1.3 on 2023-02-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rmc", "0010_rename_associated_degree_programme_course_degree"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="degree",
        ),
        migrations.AddField(
            model_name="course",
            name="associated_degree_programme",
            field=models.ManyToManyField(
                related_name="associated_degree_programme", to="rmc.degreeprogramme"
            ),
        ),
    ]
