# Generated by Django 4.1.3 on 2023-02-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rmc", "0011_remove_course_degree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="degreeprogramme",
            name="programme_courses",
            field=models.ManyToManyField(
                related_name="programme_courses", to="rmc.course"
            ),
        ),
    ]
