# Generated by Django 4.1.3 on 2023-02-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rmc", "0012_degreeprogramme_programme_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="associated_degree_programme",
        ),
        migrations.RemoveField(
            model_name="degreeprogramme",
            name="programme_courses",
        ),
        migrations.AddField(
            model_name="course",
            name="associated_degree_programmes",
            field=models.ManyToManyField(
                related_name="degree_programme_courses", to="rmc.degreeprogramme"
            ),
        ),
    ]
